title: Jiawen Liu Homepage
page-top-title: Jiawen Liu
top-section-bg-text: Be what you wanna be
home-subtitle: Jiawen Liu
copyright-text: '&copy; Jiawen Liu 2025-2027. All Rights Reserved.'
site_name: "Jiawen Liu"
site_description: "postgraduate"
email: "202321044682@mail.scut.edu.cn"
